### ISSUE TITLE
Extracting image features from 10x Visium example dataset

### ISSUE THREAD

**Issue by jeliason** [theislab/squidpy#399]
### Description

I can succesfully read in the dataset from [this link](https://support.10xgenomics.com/spatial-gene-expression/datasets/1.1.0/V1_Breast_Cancer_Block_A_Section_1) using `sc.read_visium()`. However, running `sq.im.calculate_image_features()` does not seem to work - it looks like it is possibly using the full-res spatial coordinates, instead of scaling them down for the high-res image, which is 2000x2000.

### Minimal reproducible example

```python
import scanpy as sc
import squidpy as sq

library_id = 'V1_Breast_Cancer_Block_A_Section_1'
adata = sc.read_visium('data', count_file='V1_Breast_Cancer_Block_A_Section_1_filtered_feature_bc_matrix.h5')
img = sq.im.ImageContainer(adata.uns['spatial'][library_id]['images']['hires'])
scale = 1.0
feature_name = f"features_summary_scale{scale}"
sq.im.calculate_image_features(
        adata,
        img,
        features="summary",
        key_added=feature_name,
        n_jobs=4,
        scale=scale,
    )
```

### Traceback

<details>

```pytb
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_269118/4133103645.py in <module>
      7 scale = 1.0
      8 feature_name = f"features_summary_scale{scale}"
----> 9 sq.im.calculate_image_features(
     10         adata,
     11         img,

~/anaconda3/envs/squidpy/lib/python3.8/site-packages/squidpy/im/_feature.py in calculate_image_features(adata, img, layer, library_id, features, features_kwargs, key_added, copy, n_jobs, backend, show_progress_bar, **kwargs)
     86     start = logg.info(f"Calculating features `{list(features)}` using `{n_jobs}` core(s)")
     87 
---> 88     res = parallelize(
     89         _calculate_image_features_helper,
     90         collection=adata.obs_names,

~/anaconda3/envs/squidpy/lib/python3.8/site-packages/squidpy/_utils.py in wrapper(*args, **kwargs)
    166             pbar, queue, thread = None, None, None  # type: ignore[assignment]
    167 
--> 168         res = jl.Parallel(n_jobs=n_jobs, backend=backend)(
    169             jl.delayed(runner if use_runner else callback)(
    170                 *((i, cs) if use_ixs else (cs,)),

~/anaconda3/envs/squidpy/lib/python3.8/site-packages/joblib/parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~/anaconda3/envs/squidpy/lib/python3.8/site-packages/joblib/parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~/anaconda3/envs/squidpy/lib/python3.8/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~/anaconda3/envs/squidpy/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    442                     raise CancelledError()
    443                 elif self._state == FINISHED:
--> 444                     return self.__get_result()
    445                 else:
    446                     raise TimeoutError()

~/anaconda3/envs/squidpy/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    387         if self._exception:
    388             try:
--> 389                 raise self._exception
    390             finally:
    391                 # Break a reference cycle with the exception in self._exception

ValueError: Expected `height` to be in interval `[0, 2000]`, found `15937`.
```

</details>

### Version

1.1.0

**Comment by michalk8** [comment]
Hi @jeliason ,
the issue is that you're not passing the scalefactor in the `ImageContainer` (not super obvious).The following code should fix the problem:
```python
import scanpy as sc
import squidpy as sq

library_id = 'V1_Breast_Cancer_Block_A_Section_1'

adata = sc.datasets.visium_sge(sample_id=library_id)
scale = adata.uns['spatial'][library_id]['scalefactors']['tissue_hires_scalef']
img = sq.im.ImageContainer(adata.uns['spatial'][library_id]['images']['hires'],
                           scale=scale, library_id=library_id)
feature_name = f"features_summary_scale{scale}"

sq.im.calculate_image_features(
        adata,
        img,
        features="summary",
        key_added=feature_name,
        n_jobs=4,
        # scale=1.0 by default
)
# img.interactive(adata)  # works as expected
```

I will hijack this issue to talk about the adding convenience class method `ImageContainer.from_adata` that correctly initializes the scalefactor/library_id/... from ``adata`` and some ``library_id``. Thoughts @giovp ?

**Comment by jeliason** [comment]
Ah ha, I figured I wasn't passing in a scaling factor somewhere. Thanks!

**Comment by giovp** [comment]
@michalk8 thanks for #400 , I guess it makes sense for this use case indeed.

However, I'd like to point out @jeliason that we recommend to use the high-res tissue image in tiff (or jpg) file from spaceranger. You can conveniently download it with

```
adata = scanpy.datasets.visium_sge(sample_id='V1_Breast_Cancer_Block_A_Section_1', include_hires_tiff=True)
```
It will downloaded in a `data` folder in the same path of your notebook.
You can then load it with 
```
img = squidpy.im.ImageContainer("./data/V1_Breast_Cancer_Block_A_Section_1/image.tiff")
```

the reason to use that image, and not hte one in `adata.uns['spatial'][library_id]['images']['hires']` is because the resolution is much higher and you can actually derive meaningful features from it (e.g. image features, most of the time segmentation etc.) . The `highres` image in anndata is used solely for plotting purposes (with `scanpy.pl.spatial`) as, despite being higher resolution than the `lowres` image (also in adata.uns), it's still very low , and therefore it's difficult to a. analyze and b. be confident about result interpretation.

despite the `image.tiff` being very large (sevral GB), we think that out-of-core dask implementation in the ImageContainer should make it easy to run such analysis also in a standard laptop. Let us know if you succeed or if you have any question!

**Comment by Charlottehero** [comment]
Hi, I had the same issue as above "ValueError: Expected `height` to be in interval `[0, 2000]`, found `21430`". I tried adding a scale factor but it does not solve my problem.

My code:
`library_id = '3241-OP-S1-A'
scale = 1
img = sq.im.ImageContainer("image_path",
                           scale=scale)
feature_name = f"features_summary_scale{scale}"

sq.im.calculate_image_features(
        adata,
        img,
        features="summary",
        key_added=feature_name,
        n_jobs=4,
        scale=scale
)`

**Comment by elise-smith** [comment]
Hi,
I'm having the same issue as above. 
`sq.im.calculate_image_features` works when using an uncropped image. However, when using a cropped image, I get the same error as in the original issue. Like @DaisyCuttie, I am including the scale factor when initialising the ImageContainer using the function `sq.im.ImageContainer`, however, the error still occurs.
Do you have any suggestions?
Many thanks.

**Comment by WT215** [comment]
> @michalk8 thanks for #400 , I guess it makes sense for this use case indeed.
> 
> However, I'd like to point out @jeliason that we recommend to use the high-res tissue image in tiff (or jpg) file from spaceranger. You can conveniently download it with
> 
> ```
> adata = scanpy.datasets.visium_sge(sample_id='V1_Breast_Cancer_Block_A_Section_1', include_hires_tiff=True)
> ```
> 
> It will downloaded in a `data` folder in the same path of your notebook. You can then load it with
> 
> ```
> img = squidpy.im.ImageContainer("./data/V1_Breast_Cancer_Block_A_Section_1/image.tiff")
> ```
> 
> the reason to use that image, and not hte one in `adata.uns['spatial'][library_id]['images']['hires']` is because the resolution is much higher and you can actually derive meaningful features from it (e.g. image features, most of the time segmentation etc.) . The `highres` image in anndata is used solely for plotting purposes (with `scanpy.pl.spatial`) as, despite being higher resolution than the `lowres` image (also in adata.uns), it's still very low , and therefore it's difficult to a. analyze and b. be confident about result interpretation.
> 
> despite the `image.tiff` being very large (sevral GB), we think that out-of-core dask implementation in the ImageContainer should make it easy to run such analysis also in a standard laptop. Let us know if you succeed or if you have any question!

Then what scale should I use? Many thanks!
